export const roleBasePrompts: Record<string, string> = {
  'Data Scientist': `Gauge depth in statistics, machine learning, experiment design, and real-world data engineering. Probe feature selection, model interpretability, and strategies for cleaning biased or incomplete datasets. Include LeetCode-style algorithmic coding and SQL exercises to evaluate analytical rigor. Assess ability to translate complex findings into clear business insights for both technical and non-technical stakeholders.`,
  'Software Engineer': `Examine mastery of algorithms, data structures, system design, and debugging practices. Request code walkthroughs and expect discussion of scalability, performance trade-offs, and testing strategies. Include live coding exercises to evaluate clarity of thought and code readability. Assess collaboration habits such as code reviews, version control discipline, and communication with cross-functional teams.`,
  'Product Manager': `Explore long-term product vision, prioritization frameworks, and stakeholder alignment techniques. Ask about metrics-driven decision making, experimentation strategies, and balancing user needs with business goals. Probe leadership style, roadmap communication, and handling of both successful and failed launches. Evaluate ability to synthesize feedback from engineering, design, and executives.`,
  'UX/UI Designer': `Investigate user-centered design methodology, prototyping tools, and accessibility compliance. Ask for detailed breakdowns of past design decisions, usability testing outcomes, and iteration based on research findings. Expect discussion of visual hierarchy, component libraries, and collaboration with engineers or product managers. Assess capacity to maintain design systems while delivering intuitive interfaces.`,
  'Marketing Manager': `Assess campaign strategy, audience segmentation, and creative brief development. Ask for examples of data-driven optimization, cross-channel storytelling, and ROI measurement. Explore collaboration with sales and product teams and handling of real-time market feedback. Evaluate brand positioning instincts and ability to pivot when metrics lag.`,
  'Sales Representative': `Evaluate prospecting approaches, negotiation playbooks, and pipeline management habits. Ask about tailoring demos to industry pain points, overcoming objections, and closing complex deals. Look for disciplined use of CRM tools, tracking of personal metrics, and resilience after rejection. Assess teamwork with marketing or product to refine messaging.`,
  'Business Analyst': `Probe capability to translate business objectives into analytical questions and dashboards. Ask about SQL proficiency, requirements gathering, and communicating findings to executives. Expect scenarios involving KPI definition, forecasting, and evaluating trade-offs in strategic decisions. Assess stakeholder management and iterative improvement of reports.`,
  'Customer Support Specialist': `Evaluate issue triage methodology, empathy in communication, and proficiency with support tooling. Ask about metrics such as first response time, customer satisfaction scores, and handling escalations. Explore collaboration with product teams to relay recurring issues and drive improvements. Assess ability to maintain composure with difficult customers.`,
  Nurse: `Assess patient-care expertise, familiarity with evidence-based practice, and adherence to safety protocols. Ask about interdisciplinary collaboration, handling high-stress emergencies, and use of electronic health record systems. Evaluate compassion, communication with families, and commitment to continuing education.`,
  Teacher: `Explore instructional design, classroom management strategies, and differentiation for diverse learners. Ask about assessment techniques, integration of technology, and engagement of parents or guardians. Evaluate reflection on student outcomes and pursuit of professional development.`
};

export const industryPrompts: Record<string, string> = {
  Technology: `Highlight experience with modern tooling, agile rituals, and shipping iterations quickly. Probe familiarity with cloud platforms, CI/CD pipelines, and DevOps culture. Assess understanding of security, scalability, and performance monitoring in production systems.`,
  Healthcare: `Consider HIPAA and other compliance standards, patient privacy, and ethical handling of sensitive data. Ask about clinical workflows, interoperability between health systems, and adapting technology for practitioners. Explore understanding of reimbursement models and patient engagement strategies.`,
  Finance: `Focus on risk management, regulatory compliance such as SOX or Basel, and precision of financial calculations. Investigate knowledge of trading systems, audit trails, and data privacy requirements. Expect awareness of financial instruments and market behavior.`,
  Marketing: `Emphasize campaign analytics, brand positioning, and cross-channel execution. Ask about A/B testing, attribution modeling, and storytelling aligned with customer personas. Evaluate ability to interpret audience data and pivot strategies rapidly when metrics lag.`,
  Sales: `Discuss territory planning, quota attainment, and use of CRM platforms. Probe negotiation techniques, objection handling, and post-sale relationship management. Assess alignment with marketing and product teams to refine messaging.`,
  Education: `Center on learning outcomes, curriculum design, and fostering inclusive environments. Explore experience with learning management systems, assessment tools, and adapting instruction for various modalities. Consider engagement with parents, administrators, or community programs.`,
  Consulting: `Assess structured problem-solving frameworks, slide storytelling, and client management. Ask about data-driven recommendations, stakeholder alignment, and handling ambiguous projects. Evaluate presentation skills and ability to drive consensus under tight deadlines.`,
  Retail: `Look for insight into customer experience, merchandising, and supply-chain coordination. Ask about omnichannel strategies, inventory analytics, and responding to seasonal trends. Probe team leadership and loss-prevention awareness.`,
  Manufacturing: `Probe process optimization, quality control methods, and safety compliance. Ask about lean practices, automation technologies, and coordination with suppliers. Evaluate handling of downtime, continuous improvement initiatives, and cost reduction.`,
  'Non-profit': `Explore mission alignment, fundraising tactics, and volunteer engagement strategies. Ask about grant writing, program evaluation, and operating under budget constraints. Assess ability to measure and communicate social impact to donors and stakeholders.`,
  Government: `Consider policy constraints, public accountability, and procurement rules. Ask about navigating bureaucratic processes, stakeholder communication, and implementation at scale. Evaluate commitment to transparency and adherence to regulations.`,
  Other: `Adapt questions to the candidate's context, ensuring relevance to the unique characteristics of their sector and role.`
};

export const experiencePrompts: Record<string, string> = {
  'Entry Level (0-2 years)': `Focus on foundational knowledge, academic or internship projects, and enthusiasm for learning. Expect reliance on mentorship and guidance. Ask about situations showing initiative and ability to pick up new tools quickly.`,
  'Mid Level (3-5 years)': `Expect autonomy in delivering features or analyses end-to-end. Probe collaboration across teams, handling of feedback, and examples of improving processes. Assess depth of practical experience and comfort balancing quality with deadlines.`,
  'Senior Level (6-10 years)': `Look for leadership in technical or functional domains, strategic thinking, and mentoring of juniors. Ask about scaling systems or teams, influencing stakeholders, and managing ambiguous requirements. Evaluate ability to set long-term direction while delivering short-term results.`,
  'Executive Level (10+ years)': `Assess organizational vision, cross-functional leadership, and stewardship of large portfolios. Explore how they drive cultural change, manage executives, and make high-impact decisions. Expect detailed strategies for long-term growth and risk mitigation.`
};

export function getRolePrompt(role: string, industry: string, experience: string): string | undefined {
  const roleText = roleBasePrompts[role];
  if (!roleText) return undefined;
  const industryText = industryPrompts[industry] || industryPrompts.Other;
  const experienceText = experiencePrompts[experience] || '';
  return `${roleText}\n\n${industryText}\n\n${experienceText}`.trim();
}

